### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded

### ISSUE THREAD

**Issue by wu-clan** [tusharsadhwani/yen#10]
A header error occurs when the command is executed using a VPN network.

**Comment by wu-clan** [comment]
Hi, @tusharsadhwani 

Isn't this a big problem?

**Comment by tusharsadhwani** [comment]
Can you share the terminal output? I'll look into this.

**Comment by wu-clan** [comment]
```bash
❯ yen create venv38 -p 3.8
Traceback (most recent call last):
  File "D:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\CIAN_proejcts\Github\httpfpt\venv\Scripts\yen.exe\__main__.py", line 7, in <module>
  File "D:\CIAN_proejcts\Github\httpfpt\venv\lib\site-packages\yen\cli.py", line 38, in cli
    python_version, python_bin_path = ensure_python(args.python)
  File "D:\CIAN_proejcts\Github\httpfpt\venv\lib\site-packages\yen\__init__.py", line 34, in ensure_python
    python_version, download_link = resolve_python_version(python_version)
  File "D:\CIAN_proejcts\Github\httpfpt\venv\lib\site-packages\yen\github.py", line 82, in resolve_python_version
    pythons = list_pythons()
  File "D:\CIAN_proejcts\Github\httpfpt\venv\lib\site-packages\yen\github.py", line 52, in list_pythons
    python_releases = get_latest_python_releases()
  File "D:\CIAN_proejcts\Github\httpfpt\venv\lib\site-packages\yen\github.py", line 36, in get_latest_python_releases
    with urlopen(GITHUB_API_URL) as response:
  File "D:\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "D:\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "D:\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "D:\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded
```

**Comment by wu-clan** [comment]
```bash
❯ yen create venv38 -p 3.8
Traceback (most recent call last):
  File "D:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\httpfpt\venv\Scripts\yen.exe\__main__.py", line 7, in <module>
  File "D:\httpfpt\venv\lib\site-packages\yen\cli.py", line 38, in cli
    python_version, python_bin_path = ensure_python(args.python)
  File "D:\httpfpt\venv\lib\site-packages\yen\__init__.py", line 34, in ensure_python
    python_version, download_link = resolve_python_version(python_version)
  File "D:\httpfpt\venv\lib\site-packages\yen\github.py", line 82, in resolve_python_version
    pythons = list_pythons()
  File "D:\httpfpt\venv\lib\site-packages\yen\github.py", line 52, in list_pythons
    python_releases = get_latest_python_releases()
  File "D:\httpfpt\venv\lib\site-packages\yen\github.py", line 36, in get_latest_python_releases
    with urlopen(GITHUB_API_URL) as response:
  File "D:\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "D:\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "D:\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "D:\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded
```

**Comment by tusharsadhwani** [comment]
@wu-clan this issue has been fixed in the `0.4.2` release. Can you check?

**Comment by wu-clan** [comment]
I've built and tested it locally and it looks fine, it's working!

But the json file adds 1MB directly to the package 😱

**Comment by tusharsadhwani** [comment]
Yeah, unfortunate, but I think it's fine.
