### ISSUE TITLE
create venv error: subprocess.CalledProcessError

### ISSUE THREAD

**Issue by 2niuhe** [tusharsadhwani/yen#38]
OS:Linux 6.8.0-48-generic #48-Ubuntu SMP PREEMPT_DYNAMIC
Arch: x86_64
CPU: Intel(R) Celeron(R) CPU N3450 @ 1.10GHz
Python 3.12.3

```
yen create -p 3.9.20 venv
Downloading 3.9.20 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0% • 26.2/26.2 MB • 6.1 MB/s • 0:00:00
Checksum verified!
Traceback (most recent call last):
  File "/usr/local/bin/yen", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.12/dist-packages/yen/cli.py", line 103, in cli
    create_venv(python_bin_path, args.venv_path)
  File "/usr/local/lib/python3.12/dist-packages/yen/__init__.py", line 154, in create_venv
    subprocess.run([python_bin_path, "-m", "venv", venv_path], check=True)
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/nh/.yen_pythons/3.9.20/python/bin/python3', '-m', 'venv', '/tmp/venv']' died with <Signals.SIGILL: 4>.
```

**Comment by 2niuhe** [comment]
When I run the Python in the .yen_pythons directory, it triggers a core dump.
